#!/usr/bin/env bash

CURRENT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

. ${CURRENT_DIR}/lib/connection.sh
. ${CURRENT_DIR}/lib/inventory.sh
. ${CURRENT_DIR}/lib/playbook.sh

unset CURRENT_DIR

__main() 
{
    local PLAYBOOK_FILE=${1}
    local INVENTORY=${2}
    local GROUP_TAG=${3:-all}

    readarray -t HOSTS <<< $(filter_hosts_by_tag "${INVENTORY}" "${GROUP_TAG}")

    local ENV_FILE=$(mktemp)

    if requires_elevation "${PLAYBOOK_FILE}"
    then
        ask_for_sudo_password
    fi

    for HOST_LINE in "${HOSTS[@]}" 
    do
        local SSH_HOST=$(resolve_connection_string "${HOST_LINE}")

        run_playbook "${PLAYBOOK_FILE}" "${SSH_HOST}" "${ENV_FILE}"
    done

    rm "${ENV_FILE}"
}

__main "${@}"

